### ISSUE TITLE
Show JSON Path in bottom bar of VS Code

### ISSUE THREAD

**Issue by sohang3112** [MaloPolese/copy-json-path#4]
First of all, thanks for making this extension - couldn't find any other way of doing this in VS Code!!

**Feature Request:** It would be even more awesome if the JSON Path of the key (where cursor is) always shows in the bottom bar of VS Code. This JSON Path should be updated every time the cursor location changes.  This is similar to the way [JSON Formatter Website](https://jsonformatter.org/) always shows JSON Path to current cursor location (in its right box, where the Formatted JSON shows).

**Comment by MaloPolese** [comment]
Hello, thank you for your proposal and I apologize for my response time.

However, I have trouble understanding your functionality. Maybe I'm blind but I can't find what you describe on [jsonformatter.org](https://jsonformatter.org/). Maybe you can take a screenshot for me?

Otherwise, from what I think I understand, you are talking about a feature already present in vs-code.
![image](https://user-images.githubusercontent.com/37849933/230669291-9eba0e44-0f03-4c6e-8139-f77742ae9304.png)
But the bar is at the top and not at the bottom.

I see that there are 3 like to your issue, I must surely have misunderstood your need, thank you for enlightening me :smile:

**Comment by sohang3112** [comment]
@MaloPolese I hadn't noticed the JSON path in the top bar of VS Code at the time - that's exactly what I meant. Closing the issue, since the functionality is there in VS Code.
